function init()
    CS.Aotenjo.Logger.Log("Creating Custom Material Set")

    CS.Aotenjo.LuaTileMaterialBuilder.Create("example_mod_3:ruby")
        :WithRarity(CS.Aotenjo.Rarity.COMMON)
        :OnScoringEffect(function(player, perm, tile, effects, mat)
            effects:Add(CS.Aotenjo.ScoreEffect.AddFu(20, nil))
        end)
        :OnRoundEndEffect(function(player, perm, effects, tile, mat)
            effects:Add(CS.Aotenjo.TextEffect("Ruby Power!"):OnTile(tile))
            effects:Add(CS.Aotenjo.EarnMoneyEffect(2, nil):OnTile(tile))
        end)
        :BuildAndRegister()

    CS.Aotenjo.LuaTileMaterialBuilder.Create("example_mod_3:sapphire")
        :WithRarity(CS.Aotenjo.Rarity.RARE)
        :OnScoringEffect(function(player, perm, tile, effects, mat)
            effects:Add(CS.Aotenjo.ScoreEffect.MulFan(2, nil))
        end)
        :OnRoundEndEffect(function(player, perm, effects, tile, mat)
            effects:Add(CS.Aotenjo.TextEffect("Sapphire Power!"):OnTile(tile))
            effects:Add(CS.Aotenjo.SimpleEffect("effect_sapphire", nil, (function (player)
                local newTile = CS.Aotenjo.Tile(tile)
                newTile.properties.material = CS.Aotenjo.TileMaterial.GetMaterial("example_mod:ruby")
                player:AddNewTileToPool(newTile)
            end)):OnTile(tile))
        end)
        :BuildAndRegister()
    
    CS.Aotenjo.LuaMaterialSetBuilder.Create("gemstone")
        :AddMaterial("example_mod_3:ruby")
        :AddMaterial("agate")
        :AddMaterial("crystal")
        :AddMaterial("golden")
        :AddMaterial("white_porcelain")
        :AddMaterial("jade")
        :AddMaterial("example_mod_3:sapphire")
        :BuildAndRegister()
end